config/routes.rb
Rails.application.routes.draw do

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'welcome#index'
  get 'about_us', to: 'welcome#about_us'
  get 'contact_us', to: 'welcome#contact_us'
  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end
  def new
     @post = Post.new
  end
  def create
       debugger
     end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index; end
  def about_us; end
  def contact_us; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KodaCamp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <%= link_to 'Kodacamp', root_path, class: 'navbar-brand' %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to "Home", root_path, class: "nav-link #{'active' if current_page?(root_path)}", 'aria-current': 'page' %>
          </li>
          <li class="nav-item">
            <%= link_to "About us", about_us_path, class: "nav-link #{'active' if current_page?(about_us_path)}", 'aria-current': 'page' %>
          </li>
          <li class="nav-item">
            <%= link_to "Contact us", contact_us_path, class: "nav-link #{'active' if action_name == 'contact' && controller_name == 'welcome'}", 'aria-current': 'page' %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
 <h1>Post List</h1>

 <table>
     <thead>
     <td>title</td>
     <td>content</td>
     <td>action</td>
   </thead>
     <% @posts.each do |post| %>
         <tr>
         <td><%= post.title %></td>
         <td><%= post.content %></td>
         <td></td>
       </tr>
       <% end %>
 </table>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= form_with model: @post do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <%= form.submit %>
<% end %>

app/views/welcome/about_us.erb
<h1>About us</h1>
<%= link_to 'Home', '/' %>
<%= link_to 'Contact us', '/contact_us' %>

app/views/welcome/contact_us.erb
<h1>Contact</h1>
<%= link_to 'About us', about_us_path %>
<%= link_to 'Home', root_path %>

app/views/welcome/index.html.erb
<h1>Hello World!</h1>
<p>Welcome to my page!</p>


<%= @address %>
<%= link_to 'About us', about_us_path %>
<%= link_to 'Contact us', contact_us_path %>